name: Compile latex

on:
  push:
    paths:
      - 'report/**'
      - '.github/workflows/compile_latex.yml'
  pull_request:
    paths:
      - 'report/**'
      - '.github/workflows/compile_latex.yml'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  check_latex:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: "Check report existence"
        uses: andstor/file-existence-action@v1
        id: check_report
        with:
          files: "report/main.tex"
      - name: setup python
        uses: actions/setup-python@v2
        if: steps.check_report.outputs.files_exists == 'true'
        with:
          python-version: 3.8
      - name: Install dependencies
        if: check_latex.steps.check_report.outputs.files_exists == 'true'
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with unittest discover
        if: check_latex.steps.check_report.outputs.files_exists == 'true'
        run: |
          python -m unittest
      - name: Compile LaTeX document
        if: check_latex.steps.check_report.outputs.files_exists == 'true'
        uses: dante-ev/latex-action@v0.2.0
        with:
          working_directory: report
          root_file: main.tex
      - uses: actions/upload-artifact@v2
        if: check_latex.steps.check_report.outputs.files_exists == 'true'
        with:
          name: compiled_document.pdf
          path: report/main.pdf
